// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIenMwN_jf-zWzb-ivZsIeH5H9d3FT3sg',
    appId: '1:223657645691:web:3eecc1e54de1a1a4b034de',
    messagingSenderId: '223657645691',
    projectId: 'exem4-f5b13',
    authDomain: 'exem4-f5b13.firebaseapp.com',
    storageBucket: 'exem4-f5b13.appspot.com',
    measurementId: 'G-QL2TMC50WF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpvXY1DTEcmYLo9jVL6a9Q_KSNZmsI9xE',
    appId: '1:223657645691:android:0e084da8725743bdb034de',
    messagingSenderId: '223657645691',
    projectId: 'exem4-f5b13',
    storageBucket: 'exem4-f5b13.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5O_xmaPtfzE1yQjvpvKnb4Gr5Hu47Tos',
    appId: '1:223657645691:ios:d2cced547a52a389b034de',
    messagingSenderId: '223657645691',
    projectId: 'exem4-f5b13',
    storageBucket: 'exem4-f5b13.appspot.com',
    iosBundleId: 'com.example.exam4',
  );
}
